config/routes.rb
Rails.application.routes.draw do
  get 'products/:id/buy', to: 'products#buy', as: 'product_buy'
  resources :products
  devise_for :users, controllers: {
        registrations: 'users/registrations'
      }


  get 'users/search'
  root 'products#index'
  resources :sales, only: :index


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  # before_save :buy
  belongs_to :user
  has_many :sales
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :buy]
  before_action :authenticate_user!, except: :index

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
  def buy
    if @product.sold == false
      @product.sold = true
      @product.save
      @final_sale = Sale.new(descripcion: 'vendido', user_id: current_user.id, product_id: @product.id)
      @final_sale.save
      redirect_to products_path
    end
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.sold = false

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :detalle, :descripcion, :cantindad, :precio)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :detalle %>
    <%= form.text_field :detalle %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :cantindad %>
    <%= form.number_field :cantindad %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.number_field :precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Detalle</th>
      <th>Descripcion</th>
      <th>Cantindad</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% if product.sold == false || product.sold.nil?   %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.detalle %></td>
          <td><%= product.descripcion %></td>
          <td><%= product.cantindad %></td>
          <td><%= product.precio %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% if  user_signed_in? && current_user.id != product.user_id %>
            <td><%= link_to 'Comprar', product_buy_path(product) %></td>
            <td><%= product.user.email %></td>
          <% end%>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Detalle:</strong>
  <%= @product.detalle %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @product.descripcion %>
</p>

<p>
  <strong>Cantindad:</strong>
  <%= @product.cantindad %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @product.precio %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>